### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ragurney** [orktes/go-alexa-smarthome#3]
Hi @orktes, would you mind adding a license to your repository? I'd like to use a fork of it for a personal project.

**Comment by ragurney** [comment]
Bump @orktes 🙏

**Comment by orktes** [comment]
Hi! Thanks for pointing this out. Not intentional to leave this without a proper license. Will add one in an hour or so once in front of a keyboard.

**Comment by orktes** [comment]
Hi license has now been added! Thank you!

**Comment by ragurney** [comment]
Awesome! Thanks and thanks again for the great library 👍
